#Local database, dùng ?? test
#spring.application.name=PolybookBE
#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BookStoreDB;encrypt=true;trustServerCertificate=true;
#spring.datasource.username=sa
#spring.datasource.password=123456
#spring.jpa.show-sql=true
#
#jwt.secret=polybook_secret_key_1234567890123456
#jwt.expiration=86400000

#----------------------------------------------------------

#Azure portal database, dùng ?? demo

spring.application.name=PolybookBE
spring.datasource.url=jdbc:sqlserver://bookstore-server-2024xyz.database.windows.net:1433;databaseName=bookstoreDB;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=bookstoreadmin@bookstore-server-2024xyz
spring.datasource.password=Bookstore@1234
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
jwt.secret=polybook_secret_key_1234567890123456
jwt.expiration=86400000
